[package]
name = "ratatui-wasm"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "./examples/*"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ratatui = { path = "../ratatui" }
tokio = { version = "1.32.0", default-features = false, features = ["sync"] }
crossterm = { path = "../crossterm" }
futures = "0.3.28"

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"
web-sys = "0.3.64"
xterm-js-rs = "0.1.2"
